#!/usr/bin/env ruby
#
require "bundler"

Bundler.setup

require "jekyll-reposter"


(1..3).each do |page|
  puts "Page #{page}"
  reporter = Jekyll::Reposter.new "http://notes.it-jobs-und-stellen.de/notes.atom?page=#{page}",
  :tags => "[notes, external]"

  reporter.create_if do |entry|
    true
  end
end
