#!/usr/bin/env ruby
#
require "bundler"

Bundler.setup

require "jekyll-reposter"


  reporter = Jekyll::Reposter.new "http://notes.it-jobs-und-stellen.de/notes.atom",
  :tags => "[notes, external]"

  reporter.create_if do |entry|
    true
  end
